env:
  global:
  - TERM=dumb
  - secure: Xlk4BCt6zBCjvzMCphERVrSkU80mC94kTS0hjAbgP9EcY0mHN3KyKPve6G/cCOVAXPWetZh6udFbRnpJr+tdZmi6/tRsnXQNqPO+LYt4z+vClxtYE/NrLuoeqqYuaC7zlbkpJ/2Rk9MFrC1IchS7qRGD/Y+sUbpqp4cyuYOx3d4OPLJVX+hTpWkW14tBJWu4Q46zVT8+p2+o4Kk8KMq62u+FGF3CE8aenotSUZasGMN7U5k+M7wvTitlcQMz/E5EOq0CUDDgOO2qGbHwDyCrRrqA99jIMX9yq2uFaAcQdFF0iHA94G8OgA6ewadFunuleO6aK9JY98ros6EV61r3hOoMaTiRyotF6dvj48IIfIjXh166N+falArXyifaAfbHeADE6wEoXpKXHGBj8Nxf9pWRIVPcZUKwQ+supFyhGQxdkMTmDfZuLRaPaT6zfSqEiF1EyIZMwFwR9iWpzWVLJA9AZ/c0W1EALrHmIZPW498X+mAOJb0F98GAgphEP7D9rz94SstCnvaiRECXDnuNcBiE6B6fqY8jmFSlqkRMMW0J5w5Bich3wif9jOeFsNM1EvziGdREtBldwYPSuQBEClgx1CWPqzwwVQ3PxX3ktahqvHVOHKtgBqDjrfPFm2CVqT07Qk/t/FG7xsmMa+nadeOV8pjEiWkfLzVLQgWpkcg=

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - bash

install: true
script:
- ./mvnw clean package deploy >/dev/null
- java -jar target/*-all.jar
#
- ./mvnw exec:exec

before_deploy: ./mvnw process-resources

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

cache:
  directories:
  - $HOME/.m2
