= {root-project-name} ({project-version})
////
image:https://travis-ci.org/daggerok/root-project-name.svg?branch=master["Build Status", link=github-url]
image:https://gitlab.com/daggerok/root-project-name/badges/master/build.svg["Build Status", link=gitlab-url]
image:https://img.shields.io/bitbucket/pipelines/daggerok/root-project-name.svg["Build Status", link=bitbucket-url]
////
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]

////
GitLab CI status:
image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]

BitBucket CI status:
image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]
////

== Introduction

include::../README.adoc[tags=content]

== Implementation

.plugion configuration
[source,xml]
----
include::../pom.xml[tags=content]
----

NOTE: this plugin configured for base directory: `./docs`

== Test usage

.build fat jar
[source,bash]
----
./mvnw clean process-resources
----

.run app
[source,bash]
----
npm i -g serve
serve ./target/generated-docs
open http://127.0.0.1:3000
----

== Build documentation

.build documentation
[source,bash]
----
./mvnw process-resources
----

== Links

ifdef::backend-html5[- link:./index.pdf[Documentation in PFD format]]
- link:{github-url}[GitHub repo]
- link:https://daggerok.github.io/{root-project-name}[GitHub pages]
////
- link:{gitlab-url}[GitLab repo]
- link:https://daggerok.gitlab.io/{root-project-name}[GitLab pages]
- link:{bitbucket-url}[BitBucket repo]
////

== Other links

- link:https://github.com/asciidoctor/asciidoctor-maven-plugin[asciidoctor-maven-plugin page]
- linkhttps://github.com/asciidoctor/asciidoctor-maven-plugin/issues/27#issuecomment-17471627[some asciidoctor-maven-plugin example]
